#     Llamaflow - A self service portal with runbook automation
#     Copyright (C) 2024  Whitestar Research LLC
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#      Unless required by applicable law or agreed to in writing, software
#      distributed under the License is distributed on an "AS IS" BASIS,
#      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#      See the License for the specific language governing permissions and
#      limitations under the License.


apiVersion: batch/v1
kind: Job
metadata:
  name: echo-runner
spec:
  template:
    spec:
      containers:
      - name: echo-runner
        image: ericwsr/runner-echo:4
        env:
        - name: RUNNER_ARGS
          value: "I am running in a k8s job"
        - name: POD_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: JOB_ID
          value: echo-runner
        - name: POSTBACK_HOST
          valueFrom:
            configMapKeyRef:
              name: runner-postback-url
              key: postback-url
      restartPolicy: Never
      imagePullSecrets:
      - name: regcred
  backoffLimit: 0
  podFailurePolicy:
    rules:
    - action: FailJob
      onExitCodes:
        containerName: echo-runner  
        operator: NotIn             
        values: [0]
    - action: Ignore             
      onPodConditions:
      - type: DisruptionTarget   
